#!/bin/bash

cat << 'EOF' | patch -p1
diff --git a/quartz/components/Head.tsx b/quartz/components/Head.tsx
index 3a4db10..ca55f4f 100644
--- a/quartz/components/Head.tsx
+++ b/quartz/components/Head.tsx
@@ -194,7 +194,15 @@ export default (() => {
             <meta property="twitter:url" content={socialUrl}></meta>
           </>
         )}
-        <link rel="icon" href={iconPath} />
+        <meta name="msapplication-TileColor" content="#2d89ef" />
+        <meta name="msapplication-config" content="/static/icons/browserconfig.xml" />
+        <meta name="theme-color" content="#fff" />
+        <link rel="apple-touch-icon" sizes="180x180" href="/static/icons/apple-touch-icon.png" />
+        <link rel="icon" type="image/png" sizes="32x32" href="/static/icons/favicon-32x32.png" />
+        <link rel="icon" type="image/png" sizes="16x16" href="/static/icons/favicon-16x16.png" />
+        <link rel="mask-icon" href="/static/icons/safari-pinned-tab.svg" color="#5b6cd5" />
+        <link rel="shortcut icon" href="/static/icons/favicon.ico" />
+        <link rel="manifest" href="/static/icons/site.webmanifest" />
         <meta name="description" content={description} />
         <meta name="generator" content="Quartz" />
         {css.map((resource) => CSSResourceToStyleElement(resource, true))}
EOF

cat << 'EOF' | patch -p1
diff --git a/quartz/styles/custom.scss b/quartz/styles/custom.scss
index b0c09dc..9f6322e 100644
--- a/quartz/styles/custom.scss
+++ b/quartz/styles/custom.scss
@@ -1,3 +1,17 @@
 @use "./base.scss";
 
-// put your custom CSS here!
+@media print {
+    .d-print-none {
+        display: none !important;
+    }
+
+    .d-print-none-callout {
+        & > * {
+            @extend .d-print-none
+        }
+
+        &::after {
+            content: "\2139\FE0F\00A0Présentation masquée";
+        }
+    }
+}
\ No newline at end of file
EOF

cat << 'EOF' | patch -p1
diff --git a/quartz/util/path.ts b/quartz/util/path.ts
index c02bfb1..98eb2b0 100644
--- a/quartz/util/path.ts
+++ b/quartz/util/path.ts
@@ -52,9 +52,15 @@ function sluggify(s: string): string {
     .split("/")
     .map((segment) =>
       segment
+        .toLocaleLowerCase()
+        .normalize('NFD')
+        .replace(/[\u0300-\u036f]/g, "")  // Accents
+        .replace(/\u2013|\u2014/g, "-")   // en dash, em dash
+        .replace(/'|\u2018|\u2019/g, "")  // single quotes
         .replace(/\s/g, "-")
-        .replace(/&/g, "-and-")
-        .replace(/%/g, "-percent")
+        .replace(/&/g, "-et-")
+        .replace(/%/g, "-pourcent")
+        .replace(/-{2,}/g, "-")
         .replace(/\?/g, "")
         .replace(/#/g, ""),
     )
EOF

cat << 'EOF' | patch -p1
diff --git a/quartz.config.ts b/quartz.config.ts
index dc339d9..c068fa8 100644
--- a/quartz.config.ts
+++ b/quartz.config.ts
@@ -8,17 +8,23 @@ import * as Plugin from "./quartz/plugins"
  */
 const config: QuartzConfig = {
   configuration: {
-    pageTitle: "🪴 Quartz 4.0",
+    pageTitle: "👨‍🏫 Cours",
     pageTitleSuffix: "",
     enableSPA: true,
     enablePopovers: true,
     analytics: {
-      provider: "plausible",
+      provider: "google",
+      tagId: "G-WRMKGZVHBV",
     },
-    locale: "en-US",
-    baseUrl: "quartz.jzhao.xyz",
-    ignorePatterns: ["private", "templates", ".obsidian"],
-    defaultDateType: "created",
+    locale: "fr-FR",
+    baseUrl: "cours.rihan.fr",
+    ignorePatterns: [
+      "private",
+      "templates",
+      ".obsidian",
+      "content/Réseau/Exercices"
+    ],
+    defaultDateType: "modified",
     generateSocialImages: false,
     theme: {
       fontOrigin: "googleFonts",
@@ -77,6 +83,7 @@ const config: QuartzConfig = {
     filters: [Plugin.RemoveDrafts()],
     emitters: [
       Plugin.AliasRedirects(),
+      // Plugin.CNAME(),
       Plugin.ComponentResources(),
       Plugin.ContentPage(),
       Plugin.FolderPage(),
EOF

cat << 'EOF' | patch -p1
diff --git a/quartz.layout.ts b/quartz.layout.ts
index 4a78256..a92b537 100644
--- a/quartz.layout.ts
+++ b/quartz.layout.ts
@@ -8,8 +8,7 @@ export const sharedPageComponents: SharedLayout = {
   afterBody: [],
   footer: Component.Footer({
     links: {
-      GitHub: "https://github.com/jackyzha0/quartz",
-      "Discord Community": "https://discord.gg/cRFFHYye7t",
+      GitHub: "https://github.com/max13/cours",
     },
   }),
 }
EOF