#!/bin/bash

cat << EOF | patch -d __site/zola
--- config.toml
+++ config.toml
@@ -3,7 +3,7 @@ title = "___SITE_TITLE___"
 
 build_search_index = true
 compile_sass = true
-default_language = "en"
+default_language = "fr"
 generate_feed = true
 minify_html = true
 render_emoji = true
@@ -26,7 +26,7 @@ is_netlify = true
 page_graph = "___PAGE_GRAPH___"
 title_addition = "___SITE_TITLE_TAB___"
 
-language_code = "en-US"
+language_code = "fr-FR"
 theme_color = "#fff"
 
 ganalytics = "___GANALYTICS___"
EOF

cat << EOF | patch -d __site/zola/templates/macros
--- head.html
+++ head.html
@@ -15,12 +15,16 @@
 
 
 {% macro favicons() %}
+  <meta name="msapplication-TileColor" content="#2d89ef">
+  <meta name="msapplication-config" content="{{ get_url(path="icons/browserconfig.xml") | safe }}">
   <meta name="theme-color" content="{{ config.extra.theme_color | default(value="#fff") }}">
-  <link rel="apple-touch-icon" sizes="180x180" href="{{ get_url(path="apple-touch-icon.png") | safe }}">
-  <link rel="icon" type="image/png" sizes="32x32" href="{{ get_url(path="favicon-32x32.png") | safe }}">
-  <link rel="icon" type="image/png" sizes="16x16" href="{{ get_url(path="favicon-16x16.png") | safe }}">
+  <link rel="apple-touch-icon" sizes="180x180" href="{{ get_url(path="icons/apple-touch-icon.png") | safe }}">
+  <link rel="icon" type="image/png" sizes="32x32" href="{{ get_url(path="icons/favicon-32x32.png") | safe }}">
+  <link rel="icon" type="image/png" sizes="16x16" href="{{ get_url(path="icons/favicon-16x16.png") | safe }}">
+  <link rel="mask-icon" href="{{ get_url(path="icons/safari-pinned-tab.svg") | safe }}" color="#5b6cd5">
+  <link rel="shortcut icon" href="{{ get_url(path="icons/favicon.ico") | safe }}">
   {% if not config.extra.is_netlify %}
-    <link rel="manifest" href="{{ get_url(path="site.webmanifest") | safe }}">
+    <link rel="manifest" href="{{ get_url(path="icons/site.webmanifest") | safe }}">
   {% endif %}
 {% endmacro %}
 
EOF

cat << EOF | patch -d __site/zola/templates/macros
--- footer.html
+++ footer.html
@@ -3,7 +3,11 @@
 	<div class="container">
 		<div class="row">
 			<div class="col-lg-16 order-last order-lg-first" style="text-align: center;">
-				___FOOTER___Powered by <a href="https://github.com/ppeetteerrs/obsidian-zola">obsidian-zola</a>
+				{% if __FOOTER__ %}
+				___FOOTER___
+				{% else %}
+				Powered by <a href="https://github.com/ppeetteerrs/obsidian-zola">obsidian-zola</a>
+				{% endif %}
 			</div>
 		</div>
 	</div>
EOF

cat << EOF | patch -d __site/zola/templates/macros
--- docs-sidebar.html
+++ docs-sidebar.html
@@ -1,5 +1,5 @@
 {% macro docs_sidebar(current_section) %}
-<div class="col-lg-5 col-xl-4 docs-sidebar">
+<div class="col-lg-5 col-xl-4 docs-sidebar d-none"> <!-- d-xl-block ? -->
 	<nav class="docs-links" aria-label="Main navigation">
 			{% set index_path = current_section ~ "/_index.md" | trim_start_matches(pat="/") %}
 			{% set index = get_section(path=index_path) %}
EOF

cat << EOF | patch -d __site/zola/templates/macros
+++ docs-toc.html
--- docs-toc.html
@@ -1,5 +1,5 @@
 {% macro docs_toc(page) %}
-  <nav class="docs-toc d-none d-xl-block col-xl-3" aria-label="Secondary navigation">
+  <nav class="docs-toc col" aria-label="Secondary navigation">
   	<div class="page-links">
   			<h3>On this page</h3>
   			<nav id="TableOfContents">
EOF

cat << EOF | patch -d __site/zola/sass/common
--- _global.scss
+++ _global.scss
@@ -139,7 +139,7 @@ body {
 }
 
 .docs-toc {
-  order: 2;
+  /* order: 2; */
 }
 
 @supports ((position:-webkit-sticky) or (position:sticky)) {
EOF

cat << EOF | patch -d __site/zola/templates/docs
--- page.html
+++ page.html
@@ -17,7 +17,7 @@
 	  {{ macros_sidebar::docs_sidebar(current_section=current_section) }}
 	  {{ macros_toc::docs_toc(page=page) }}
       <main class="docs-content col-lg-11 col-xl-9">
-        <h1>{{ page.title | safe }}</h1>
+        <!-- <h1>{{ page.title | safe }}</h1> -->
         {% if page.extra.lead %}<p class="lead">{{ page.extra.lead | safe }}</p>{% endif %}
         {{ page.content | safe }}
         {% if config.extra.edit_page %}
EOF

cat << EOF | patch -d __site/zola/templates/macros
--- docs-toc.html
+++ docs-toc.html
@@ -1,7 +1,7 @@
 {% macro docs_toc(page) %}
   <nav class="docs-toc d-none d-xl-block col-xl-3" aria-label="Secondary navigation">
   	<div class="page-links">
-  			<h3>On this page</h3>
+  			<h3>Sommaire</h3>
   			<nav id="TableOfContents">
   					<ul>
   							{% for h1 in page.toc %}
EOF
