name: Obsidian to gh-pages

on: [push]

permissions:
  contents: write

jobs:
  build-and-deploy-obsidian:
    runs-on: ubuntu-latest
    steps:
      - name: Update system
        run: sudo apt update && sudo apt remove -y python3.8 && sudo apt install -y python3.9 python3.9-distutils && curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && python3.9 get-pip.py

      - name: Install obsidianhtml
        run: pip install --upgrade pip && pip install obsidianhtml

      - name: Patch obsidianhtml
        run: |
          cat << EOF | patch -d "$(pip show obsidianhtml | grep Location: | cut -d' ' -f2)/obsidianhtml"
          --- ConvertVault.py
          +++ ConvertVault.py
          @@ -689,6 +689,29 @@
           
                   print('< EXPORTING USER FILES: Done')
           
          +    if pb.gc('dir_exports'):
          +        dir_exports = pb.gc('dir_exports')
          +        if not isinstance(dir_exports, list):
          +            raise Exception(f'Config value type of dir_exports should be list, instead of {type(dir_exports).__name__}.')
          +
          +        print('> EXPORTING USER DIRECTORIES')
          +
          +        for udir in dir_exports:
          +
          +            src = pb.paths['obsidian_folder'].joinpath(udir['src']).resolve()
          +            dst = pb.paths['html_output_folder'].joinpath(udir.get('dst', '')).joinpath(src.as_posix().split('/')[-1]).resolve()
          +            if not src.exists():
          +                raise Exception(f'Directory {src.as_posix()} not found')
          +
          +            print(f"\tWriting {src.as_posix()} to {dst.as_posix()}")
          +
          +            if dst.exists():
          +                shutil.rmtree(dst)
          +
          +            shutil.copytree(src, dst, dirs_exist_ok=True)
          +
          +        print('< EXPORTING USER DIRECTORIES: Done')
          +
               print('\nYou can find your output at:')
               if pb.gc('toggles/compile_md'):
                   print(f"\tmd: {pb.paths['md_folder']}")
          @@ -798,6 +821,7 @@
               # Url is used so you can open the note/node by clicking on it
               node['url'] = pb.gc("html_url_prefix") + '/' + rel_dst_path.as_posix()
               node['rtr_url'] = rel_dst_path.as_posix()
          +    node['title'] = node['url'].split('/')[-1].removesuffix('.html')
               pb.network_tree.AddNode(node)
          
               # Backlinks are set so when recursing, the links (edges) can be determined
          @@ -1069,6 +1093,8 @@
               html = html.replace('{pinnedNode}', node['id'])\\
                          .replace('{html_url_prefix}', html_url_prefix)\\
                          .replace('{page_depth}', str(page_depth))\\
          +               .replace('{node_title}', node['title'])\\
          +               .replace('{node_url}', node['url'][1:])\\
           
               # [?] Documentation styling: Navbar
               # ------------------------------------------------------------------
          EOF
          cat << EOF | patch -d "$(pip show obsidianhtml | grep Location: | cut -d' ' -f2)/obsidianhtml/src"
          --- defaults_config.yml
          +++ defaults_config.yml
          @@ -100,6 +100,12 @@
           #   - src: Resources/Includes/christmas_snowflakes.js
           #     dst: obs.html/static/christmas_snowflakes.js
           
          +dir_exports: []
          +# dir_exports:
          +#   - src: Resources/Includes/css
          +#   - src: Resources/Includes/icons
          +#     dst: obs.html
          +
           ##########################################################################
           #                    OPTIONAL BEHAVIOR / FEATURES                        #
           ##########################################################################
          EOF

      - name: Checkout
        uses: actions/checkout@v3

      - name: Run obsidianhtml
        run: obsidianhtml convert -i config.yml

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: output/html
