# On every push this script is executed
on:
  push:
    branches:
      - master
name: Build and push obisidan-zola to gh-pages branch 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build_and_deploy
        # In the spot where it says v0.1.3.1-alpha, update that to the latest release tag on a new release
        uses: max13/obsidian-zola-build-action@v0.1.3.3
        env:
          # Target branch
          PAGES_BRANCH: gh-pages
          # Provide personal access token
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
