name: Build Quartz site for GitHub Pages
 
on:
  push:
    branches:
      - master
 
permissions:
  contents: read
  pages: write
  id-token: write
 
concurrency:
  group: "pages"
  cancel-in-progress: false
 
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Quartz
        uses: actions/checkout@v4
        with:
          repository: jackyzha0/quartz
      - run: rm -rf content
      - name: Checkout Obsidian
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for git info
          path: content
      - name: Start post-checkout script
        run: |
          if [ -x ./content/.scripts/post-checkout ]; then
            echo "Post-Checkout"
            ./content/.scripts/post-checkout
          fi
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Dependencies
        run: npm ci
      - name: Start pre-build script
        run: |
          if [ -x ./content/.scripts/pre-build ]; then
            echo "Pre-Build"
            ./content/.scripts/pre-build
          fi
      - name: Build Quartz
        run: npx quartz build
      - name: Start post-build script
        run: |
          if [ -x ./content/.scripts/post-build ]; then
            echo "Post-Build"
            ./content/.scripts/post-build
          fi
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public
 
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4